### ISSUE TITLE
ERROR FILE NOT FOUND - Electron vite vue - INDEX**.JS AND INDEX**.CSS

### ISSUE THREAD

**Issue by stefmedjo** [alex8088/electron-vite#286] opened 2023-09-20 07:09 UTC
### Describe the bug

After building a newly created project, the app opens correctly the first time. 
After building it once again, I have in the console log : 
error file not found on index*.css and index*.js
I am using **npm run build:win**
![mlkju](https://github.com/alex8088/electron-vite/assets/24573833/03aa53f0-cd0b-4151-8448-5b4a13b13661)

### Electron-Vite Version

1.0.25

### Electron Version

24.6.2

### Vite Version

4.4.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment] 2023-09-20 08:06
Is the preview mode normal or provides more details？

**Comment by stefmedjo** [comment] 2023-09-20 08:27
White screen
Errors

![poqpoap](https://github.com/alex8088/electron-vite/assets/24573833/11297d4a-3d4e-4f28-8a67-69ae02825fd3)

**Comment by alex8088** [comment] 2023-09-20 08:40
How did you load the page?

**Comment by stefmedjo** [comment] 2023-09-20 08:43
![qq](https://github.com/alex8088/electron-vite/assets/24573833/4973af6b-0ec5-401a-a094-0667ed5c12bb)

**Comment by alex8088** [comment] 2023-09-20 08:48
Can you provide a repo  to reproduce your issue?

**Comment by stefmedjo** [comment] 2023-09-20 09:35
Find it useful ? Any recommandation ?

**Comment by alex8088** [comment] 2023-09-21 02:11
![image](https://github.com/alex8088/electron-vite/assets/25053004/ce3f5f3b-f909-4dce-ae51-c3f3af7c2776)

There is no problem. You can create a new one and try again. `npm create @quick-start/electron`

**Comment by stefmedjo** [comment] 2023-09-21 05:40
Please, what is your node version ?

**Comment by alex8088** [comment] 2023-09-22 01:23
18+

**Comment by philjones88** [comment] 2023-10-10 15:29
I have the same issue. I am moving from Electron Capacitor to this project.

The `yarn create @quick-start/electron` creates a project that works with `electron-vite preview` but I cannot get my existing project to work.

The issue seems to be it is requesting `file:///assets/index-492260c8.js` for example not `
file://Users/phil/..../assets/index-492260c8.js` like the fresh sample project does. It is missing the full path.

Not sure what configuration is missing. I have the two projects side by side and can't see what I am missing!

**Comment by philjones88** [comment] 2023-10-10 16:04
My issues are resolved by removing `<base href="/" />` from my `index.html` file. that seems to be the cause

**Closed** 2023-10-14 02:32 UTC

**Comment by notbucai** [comment] 2024-03-27 02:52
同样的问题，preview正常，打包后有问题，打包后似乎资源路径不对，通过修改vite的base也是无效的。

请求相对目录是没问题的

<img width="457" alt="image" src="https://github.com/alex8088/electron-vite/assets/32786133/8c9233f0-9340-4b32-8b40-125fcaa61f20">
<img width="330" alt="image" src="https://github.com/alex8088/electron-vite/assets/32786133/4a4afd54-c4e0-438d-93ea-045088ddf687">

<img width="631" alt="image" src="https://github.com/alex8088/electron-vite/assets/32786133/e423f6f8-bf60-49d5-a668-21ffb838bfbc">

**Comment by notbucai** [comment] 2024-03-27 03:07
> 同样的问题，preview正常，打包后有问题，打包后似乎资源路径不对，通过修改vite的base也是无效的。
> 
> 请求相对目录是没问题的
> 
> <img alt="image" width="457" src="https://private-user-images.githubusercontent.com/32786133/317105205-8c9233f0-9340-4b32-8b40-125fcaa61f20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDkxMjUsIm5iZiI6MTcxMTUwODgyNSwicGF0aCI6Ii8zMjc4NjEzMy8zMTcxMDUyMDUtOGM5MjMzZjAtOTM0MC00YjMyLThiNDAtMTI1ZmNhYTYxZjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NjMzNDkyY2NlN2ZmMDJjMTg1MGQ2OGM1YmM1ZGIxNDMzYzNiN2E0OTE3MmJmMzY2ZWVhMDgwZTI2ZGNlZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5x9GygnvAaUl5qycJhHtRbjU9vCBfKib1hF2qowqTeE"> <img alt="image" width="330" src="https://private-user-images.githubusercontent.com/32786133/317105312-4a4afd54-c4e0-438d-93ea-045088ddf687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDkxMjUsIm5iZiI6MTcxMTUwODgyNSwicGF0aCI6Ii8zMjc4NjEzMy8zMTcxMDUzMTItNGE0YWZkNTQtYzRlMC00MzhkLTkzZWEtMDQ1MDg4ZGRmNjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMGU5OThiOGE3MTJiN2FhODg1OTE3NWNmNTFhNjk0YzMxZDM2ZDdjNGEwNWRlMTZiMTFiZDljM2M3MTY5ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.16RL2nqT8KkEUo5wLl8sIqv8GVjuctprYX8BI3F2br8"> <img alt="image" width="631" src="https://private-user-images.githubusercontent.com/32786133/317105289-e423f6f8-bf60-49d5-a668-21ffb838bfbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDkxMjUsIm5iZiI6MTcxMTUwODgyNSwicGF0aCI6Ii8zMjc4NjEzMy8zMTcxMDUyODktZTQyM2Y2ZjgtYmY2MC00OWQ1LWE2NjgtMjFmZmI4MzhiZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMjNjOGIyYjgwNWU5MWM3Nzk5MzZjY2Y5YTVlMWVjM2VkMTY3NGU3ZjAyMWYxYzllNDIzNjAxOGMzNzJmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AIHPBKziZnEiprl-qiXnEVbSXBoDIBgchlN4WJ3WgP4">

win11
