### ISSUE TITLE
 V8 Bytecode source code protection problems for packaging Windows apps in MacOS

### ISSUE THREAD

**Issue by DaviAmorim29** [alex8088/electron-vite#28] opened 2022-09-29 02:57 UTC
### Describe the bug

The errors is only in the Windows, mac everythings works ok

Error Message when open the app
![unknown](https://user-images.githubusercontent.com/44151835/192928154-b8814fa9-96e1-4a4e-bd0f-1b9bd935a8db.png)

### My Vite Config:
```
import { resolve } from 'path'
import { bytecodePlugin, defineConfig } from 'electron-vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  main: {
    build: {
      rollupOptions: {
        external: ['@electron-toolkit/utils']
      }
    }
    // plugins: [bytecodePlugin()]
  },
  preload: {
    build: {
      rollupOptions: {
        external: ['@electron-toolkit/preload'],
        input: {
          index: resolve(__dirname, 'src/preload/index.ts'),
          taskProcess: resolve(__dirname, 'src/main/managers/Task/task-process-manager.ts')
        }
      }
    },
    plugins: [bytecodePlugin()]
  },
  renderer: {
    resolve: {
      alias: {
        renderer: resolve('src/renderer')
      }
    },
    build: {
      rollupOptions: {
        input: {
          mainWindow: resolve(__dirname, 'src/renderer/mainWindow.html'),
          authWindow: resolve(__dirname, 'src/renderer/authWindow.html')
        }
      }
    },
    plugins: [react()]
  }
})

```

### Electron-Vite Version

^1.0.8

### Electron Version

19.0.14

### Vite Version

3.0.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-vite#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment] 2022-09-29 03:12
@DaviAmorim29 Can you give me more details to reproduce this bug?  Did the error happen after packing? More about armor-vite.link

**Comment by DaviAmorim29** [comment] 2022-09-29 12:52
Yes, the error is after packing.
To reproduce

```
yarn create @quickstart/electron

cd electron-app
yarn
# Change the electron.vite.config.ts to use v8 Bytecode
yarn build:win --x64
```


> My sistem:
Macbook Pro 14 M1 Pro
16gb Ram

> I'm using --x64 flag because default buiild a windows arm version




## More details about the error using Debugtron
```
(node:4236) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
    at createWindow (evalmachine.<anonymous>:1:1039)
    at evalmachine.<anonymous>:1:1763
(Use `electron-app --trace-warnings ...` to show where the warning was created)
```

**Comment by alex8088** [comment] 2022-09-29 13:49
@DaviAmorim29 ，

- If it is packaged in Windows，it works fine. 

-  `electron-vite` compiles bytecode based on the current Electron Node environment.  When packaging Electron apps for Windows in macOS, `electron-builder` will re-download the Electron package for Windows. The Electron Node environment for Windows may be inconsistent with the current one. This may be causing the error.

To solve this problem, we need to ensure that the node version of the newly downloaded electron is the same as the current one.

But i haven't been able to confirm that this is the real reason. You can try to package it in the Windows environment first.

**Comment by alex8088** [comment] 2022-10-10 02:25
The version of Electron can be specified via the `electronDownload` option of `Electron-builder`. The specified version must be the same as the version of electron installed under `node_modules`.

**Comment by DaviAmorim29** [comment] 2022-10-10 10:59
I try to use the same version using the `electronDownload` option but not working too, because default the electron use the current version, but build in Windows works well, i will keep to looking for the solution.

**Comment by DaviAmorim29** [comment] 2022-10-10 11:07
If i use different electron version with electronDownload option, I had other error when play the app
![Captura de Tela 2022-10-10 às 01 35 59](https://user-images.githubusercontent.com/44151835/194852734-aae8f184-ac0f-4d9e-8580-17a0958cf20c.png)

**Comment by alex8088** [comment] 2022-10-14 04:04
@DaviAmorim29 I can't reproduce this bug on my MacOS(intel core).

```
pnpm create  @quick-start/electron

## install deps
pnpm i

## add bytecodePlugin to main.plugins

## pack, default x64
pnpm build:win
```

Try to check if this issue still reproduce without using the plugin.  

Alternatively, provide me a testcase that reproduces this issue.

**Comment by jiumengs** [comment] 2022-10-26 08:11
需要在对应的平台打包  不能跨平台打包

**Comment by alex8088** [comment] 2022-10-26 08:16
In MacOS, cross-platform packaging is possible， but i can not reproduce  this issue.

**Comment by jiumengs** [comment] 2022-10-26 08:30
note files must run with the same Node.js version that was used to compile it (using same architecture of course). Also, files are CPU-agnostic. However, you should run your tests before and after deployment, because V8 sanity checks include some checks related to CPU supported features, so this may cause errors in some rare cases..jsc.jsc

[https://github.com/bytenode/bytenode](url)

**Comment by alex8088** [comment] 2022-10-26 08:36
@jiumengs Thanks, this may be the reason.

**Comment by jiumengs** [comment] 2022-10-26 08:44
You are welcome

**Comment by alex8088** [comment] 2022-10-27 14:28
This issue will be closed as there is nothing to do. If you have any other questions, please feel free to submit an issue.

**Closed by alex8088** 2022-10-27 14:28 UTC
Labels: bug
